train_params: 
  Episode_length : 200
  N_episodes : 20
  epsilon: 0.1
  alpha: 0.1
  gamma: 0.99

action_count_buyer : 7
action_count_seller : 12

gas_fees_params: 
  - initial_gas_fees: 1.4
  - ceiling_gas_fees: 4
  - floor_gas_fees: 1.4
  - congestion_factor : 0.1

nft_volume_params: 
  initial_nft_volumes:   # Initial NFT volumes for rarity scores (1-5)
    - 40
    - 20
    - 20
    - 10
    - 100
  volatility : 0.1
  shock_prob : 0.1

state_dim_sellers : 
  - 5
  - 5
  - 5
  - 5

state_dim_buyers :
  - 5
  - 5
  - 5
  - 5

Num_sellers : 2
Num_buyers : 2

buyers_config:
  - BuyerID: 0
    AvailableFunds: 10
    total_rewards_achieved: 0
  
  - BuyerID: 1
    AvailableFunds: 100
    total_rewards_achieved: 0

sellers_config:
  - NFT_config:
      NFT_params:
        nft_artwork_id: 0
        BasePrice: 10
        CurrPrice: 10
        RarityScore: 3
        TimeListed: 0
      SellerID: 0
      pricing_variability_level : 5
      max_percentage_change : 20
      reward : 0
  - NFT_config:
      NFT_params:
        nft_artwork_id: 0
        BasePrice: 10
        CurrPrice: 10
        RarityScore: 3
        TimeListed: 0
      SellerID: 0
      pricing_variability_level : 4
      max_percentage_change : 20
      reward : 0

