train_params: 
  Episode_length : 200
  N_episodes : 50
  epsilon: 0.4
  alpha: 0.5
  gamma: 0.99

action_count_buyer : 7
action_count_seller : 12

seller_discretization_params: 
  curr_price:
    min: 0
    max: 100
    n_bins: 5
  rarity_score:
    min: 1
    max: 5
    n_bins: 5
  time_listed:
    min: 0
    max: 100
    n_bins: 5
  pricing_variability_level:
    min: 0
    max: 5
    n_bins: 5
  max_percentage_change:
    min: 1
    max: 20
    n_bins: 5

buyer_discretization_params:
  available_funds:
    min: 0
    max: 100
    n_bins: 5

gas_fees_params: 
  initial_gas_fees: 50
  ceiling_gas_fees: 700
  floor_gas_fees: 20
  congestion_factor : 1.5
  n_bins: 5

nft_volume_params: 
  initial_nft_volumes:   # Initial NFT volumes for rarity scores (1-5)
    - 4000
    - 880
    - 10000
    - 800
    - 90
  volatility : 0.07
  shock_prob : 0.03

state_dim_sellers : 
  - 5
  - 5
  - 5
  - 5

state_dim_buyers :
  - 5
  - 5
  - 5
  - 5

Num_sellers : 2
Num_buyers : 2

buyers_config:
  - BuyerID: 0
    AvailableFunds: 57
    total_rewards_achieved: 0
  
  - BuyerID: 1
    AvailableFunds: 86
    total_rewards_achieved: 0
    
sellers_config:
  - NFT_config:
      NFT_params:
        nft_artwork_id: 0
        BasePrice: 23
        CurrPrice: 23
        RarityScore: 3
        TimeListed: 0
      SellerID: 0
      pricing_variability_level : 5
      max_percentage_change : 10
      reward : 0
  - NFT_config:
      NFT_params:
        nft_artwork_id: 1
        BasePrice: 80
        CurrPrice: 80
        RarityScore: 4
        TimeListed: 0
      SellerID: 1
      pricing_variability_level : 5
      max_percentage_change : 10
      reward : 0

