layer_0_params : 
  llm_model : "llama-3.3-70b-versatile"
  retries : 2
  max_experts_per_objective : 2

available_experts: 
  - DAO_expert
  - DID_expert
  - DeFi_expert
  - NFT_expert

coder_params : 
  llm_model : "llama-3.3-70b-versatile"
  retries : 4
  max_parallel_coders : 3
  save_dir : "database"